# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-target-cluster
spec:
  description: "Target PostgreSQL cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  instances: 3
  startDelay: 300
  primaryUpdateStrategy: unsupervised
  postgresql:
    pg_hba:
      - host all all 10.48.0.0/20 md5
      - host all all 10.54.0.0/20 md5
  enableSuperuserAccess: true
  superuserSecret:
    name: superuser-secret
  bootstrap:
    pg_basebackup:
      source: my-source-cluster
  replica:
    enabled: true
    source: my-source-cluster
  externalClusters:
  - name: my-source-cluster
    connectionParameters:
      host: my-source-cluster-rw-headless.pg-ns.svc.postgres-source.local
      user: postgres
      dbname: postgres
    password:
      name: superuser-secret
      key: password
  storage:
    storageClass: premium-rwo
    size: 2Gi
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  affinity:
    enablePodAntiAffinity: true
    tolerations:
    - key: "app.stateful/component"
      effect: NoSchedule
      value: "postgres-operator"
      operator: "Equal"
    additionalPodAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: "app.stateful/component"
              operator: In
              values:
              - "postgres-operator"
          topologyKey: "topology.kubernetes.io/zone"
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Service
metadata:
  name: my-target-cluster-ro-headless
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: my-target-cluster
    role: replica
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-target-cluster-rw-headless
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: my-target-cluster
    role: primary
  type: ClusterIP

