# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_postgresql_cloudnativepg_operator_postgres_cluster]
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gke-pg-cluster
spec:
  description: "Standard GKE PostgreSQL cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0
  instances: 3
  startDelay: 300
  primaryUpdateStrategy: unsupervised

# [START gke_databases_postgresql_cloudnativepg_operator_postgres_cluster_parameters]
  postgresql:
    parameters:
      # shared_buffers: "256MB"
      # effective_cache_size: "512MB"
      # max_connections: "100"
      password_encryption: scram-sha-256
    pg_hba:
      - host all all all md5
# [END gke_databases_postgresql_cloudnativepg_operator_postgres_cluster_parameters]

  bootstrap:
    initdb:
      database: app

# [START gke_databases_postgresql_cloudnativepg_operator_postgres_cluster_volume]
  storage:
    storageClass: premium-rwo
    size: 10Gi
# [END gke_databases_postgresql_cloudnativepg_operator_postgres_cluster_volume]

  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi

  affinity:
    enablePodAntiAffinity: true

    tolerations:
    - key: cnpg.io/cluster
      effect: NoSchedule
      value: gke-pg-cluster
      operator: Equal

    additionalPodAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.component
              operator: In
              values:
              - "pg-cluster"
          topologyKey: topology.kubernetes.io/zone
# [END gke_databases_postgresql_cloudnativepg_operator_postgres_cluster]
