# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_postgresql_cloudnativepg_operator_postgres_pooler]
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: gke-pg-pooler-rw
spec:
  cluster:
    name: gke-pg-cluster
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "100"
      default_pool_size: "20"
  template:
    spec:
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
      tolerations:
      - key: cnpg.io/cluster
        effect: NoSchedule
        value: gke-pg-cluster
        operator: Equal
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.component
                  operator: In
                  values:
                  - "pg-cluster"
              topologyKey: topology.kubernetes.io/zone
# [END gke_databases_postgresql_cloudnativepg_operator_postgres_pooler]
